### ISSUE TITLE
Swap from `cron` to `croner-rust`  - Support wider range of cron features

### ISSUE THREAD

**Issue by MGough** [mvniekerk/tokio-cron-scheduler#74]
The `cron` library is quite a strict implementation, which makes some things like 'run on the last day of each month' or 'run on the 3rd wednesday of each month' tricky, amongst others.

[Croner](https://github.com/Hexagon/croner-rust) seems to have wider support, so allowing it to be used instead of `cron` would be great. Perhaps it might even be possible to select which cron library to use?

I'm happy to try to help out with a move to Croner if it's likely to be merged rather than sit as an open PR, just let me know!

**Comment by mvniekerk** [comment]
Yes a PR will be welcomed, thank you!

Groete / Best regards
Michael van Niekerk
________________________________
Van: Merlin Gough ***@***.***>
Gestuur: Thursday, August 8, 2024 2:21:25 PM
aan: mvniekerk/tokio-cron-scheduler ***@***.***>
Aa: Subscribed ***@***.***>
onderwerp: [mvniekerk/tokio-cron-scheduler] Swap from `cron` to `croner-rust` - Support wider range of cron features (Issue #74)


The cron library is quite a strict implementation, which makes some things like 'run on the last day of each month' or 'run on the 3rd wednesday of each month' tricky, amongst others.

Croner<https://github.com/Hexagon/croner-rust> seems to have wider support, so allowing it to be used instead of cron would be great. Perhaps it might even be possible to select which cron library to use?

I'm happy to try to help out with a move to Croner if it's likely to be merged rather than sit as an open PR, just let me know!
