### ISSUE TITLE
Integrate english-to-cron crate 

### ISSUE THREAD

**Issue by kaplanelad** [mvniekerk/tokio-cron-scheduler#79]
It would be beneficial to integrate the [english-to-cron](https://crates.io/crates/english-to-cron) crate into your library to allow users to generate cron expressions using plain English text.
This would enhance the usability of your library by making it easier for developers who are less familiar with cron syntax to define scheduling rules.

if this is something that you want, I'd love to open a PR for that

**Comment by mvniekerk** [comment]
Hi @kaplanelad 
I've tried to do it in the [english-to-cron-integration](https://github.com/mvniekerk/tokio-cron-scheduler/tree/english-to-cron-integration) branch in a non-destructive way. It seems like the existing croner parsing is failing after using this.

**Comment by kaplanelad** [comment]
Hey @mvniekerk,
Do you have a text example that converted wrong?

**Comment by mvniekerk** [comment]
If you run the simple example with the English feature enabled

Groete / Best regards
Michael van Niekerk
________________________________
Van: Elad Kaplan ***@***.***>
Gestuur: Saturday, September 21, 2024 6:29:45 PM
aan: mvniekerk/tokio-cron-scheduler ***@***.***>
Aa: Michael van Niekerk ***@***.***>; Mention ***@***.***>
onderwerp: Re: [mvniekerk/tokio-cron-scheduler] Integrate english-to-cron crate (Issue #79)


Hey @mvniekerk<https://github.com/mvniekerk>,
Do you have a text example that converted wrong?

**Comment by kaplanelad** [comment]
I noticed that you added the text `every 10 seconds`, which the library correctly converts into the cron syntax `0/10 * * * * ? *`.

I have also tested the cron expression `0/10 * * * * ? *`  directly with the library, and it executes as expected.

**Comment by kaplanelad** [comment]
It seems the syntax generator is functioning properly. However, when I debug it on your branch, I encounter the following error:
```
Pattern must consist of five fields, seconds are not allowed by configuration.
```

**Comment by mvniekerk** [comment]
Ok, so it seems like croner-rust doesn't like the year field. I've noticed you're the author of english-to-cron - thank you for this!
v0.13.0 will have the crate included

**Comment by kaplanelad** [comment]
@mvniekerk, why did you add it as a feature flag and as part of the base features?
this crate is very small

**Comment by mvniekerk** [comment]
Hi Elad
I had previous bug reports of minimizing crate imports and feature gating, so this goes with that spirit. Since this pulls in extra crates and adds parsing complexity, I’d rather give people what they had and not something they didn’t asked for.
I do think that the existence of the feature is quite obvious in the README, which will make it more discoverable.

From: Elad Kaplan ***@***.***>
Date: Sunday, 22 September 2024 at 14:22
To: mvniekerk/tokio-cron-scheduler ***@***.***>
Cc: Michael van Niekerk ***@***.***>, Mention ***@***.***>
Subject: Re: [mvniekerk/tokio-cron-scheduler] Integrate english-to-cron crate (Issue #79)

@mvniekerk<https://github.com/mvniekerk>, why did you add it as a feature flag and as part of the base features?
this crate is very small
